### ISSUE TITLE
The babel preset breaks Symbol.* method calls (Symbol.for)

### ISSUE THREAD

**Issue by futpib** [react/metro#218]
**Do you want to request a *feature* or report a *bug*?**

*bug*

**What is the current behavior?**

Babel input:

```js
Symbol.for('bar');
```

Babel output:
```js
(typeof Symbol === "function" ? Symbol.for : "@@for")('bar');
```

In React Native runtime that code results in this error:
```
TypeError: @@for is not a function (evaluating '(typeof Symbol === 'function' ? typeof Symbol === "function" ? Symbol.for : "@@for" : '@@for')('bar')
```

Seems like [packages/metro-react-native-babel-preset/src/transforms/transform-symbol-member.js](https://github.com/facebook/metro/blob/a8029764a622eb166c25436a54ad93c891ab70af/packages/metro-react-native-babel-preset/src/transforms/transform-symbol-member.js) is the transform that introduces this.

The workaround I used was to include `core-js/es6/symbol` `Symbol` polyfill.

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**

https://github.com/futpib/metro-issue-218-demo

Running `yarn && yarn test` in that repo will output the broken code.

**What is the expected behavior?**

Either fix the transform (should only transform well-known symbols like `Symbol.hasInstance` but not other properties like `Symbol.for`) or maybe provide an implementation (or polyfill) of `Symbol` and ditch the transform.

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**

Seems irrelevant, but will provide if asked.

**Comment by gsklee** [comment]
Always happens to me, and I could no longer get the proposed workaround to work in core-js v3.1.4.

**Comment by robhogan** [comment]
We’re triaging older issues. `metro-react-native-babel-preset` has been replaced by `@react-native/babel-preset`, so this question no longer applies to supported React Native versions.
