### ISSUE TITLE
metro-visualizer error: can't work with RN 0.58.6

### ISSUE THREAD

**Issue by roytan883** [react/metro#373]
**Do you want to request a *feature* or report a *bug*?**

*metro-visualizer bug*

**What is the current behavior?**

```
console log show: 
UnhandledPromiseRejectionWarning: TypeError: metroServer.getPlatforms is not a function
    at xxx\node_modules\metro-visualizer\src\middleware\routes.js:134:44
TypeError: metroServer.getVisualizerConfig is not a function
    at xxx\node_modules\metro-visualizer\src\middleware\routes.js:188:44

and the visualizer can't work
```

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**

```
1, yarn add metro-visualizer
2, set
"metro": {
    "server": {
      "enableVisualizer": true
    }
  }
3, run and visit 
yarn start
http://localhost:8081/visualizer

```

**What is the expected behavior?**

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**

"metro-visualizer": "0.53.0",

**Comment by roytan883** [comment]
seems i need udpate metro and metro-core

**Comment by roytan883** [comment]
still can't work, I found the RN 0.58.6 internal use `"metro": "^0.49.1",`
after i add `"metro-visualizer": "0.53.0"` , it can't work.

If i start by `react-native run-android`, when access visualizer console show errors:
```
TypeError: metroServer.getPlatforms is not a function
```

If i start by `yarn run metro serve`, when access visualizer, the web is OK, but when click `build`, it show error:
```
Module `AccessibilityInfo` does not exist in the Haste module map
```

how can i use make `metro 0.53.0` work with `RN 0.58.6` ?

**Comment by robhogan** [comment]
Sorry this never got a response. You needed to install `metro-visualizer` at exactly the same version as the bundled Metro with your RN version - 0.49.1 in this case.

`metro-visualizer` was removed completely in Metro 0.57 / RN 0.62. For anyone else seeing this - try Expo Atlas.
